<?php

namespace Letunovskiymn\PoemsBundle\Repository;

use Letunovskiymn\PoemsBundle\Entity\Poem;


/**
 * PoemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoemRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Случайные записи из базы
     *
     * @return array
     */
    public function getRandomPoems(){
        $poems = $this->createQueryBuilder('p')
            ->groupBy('p.position')
            ->getQuery()
            ->getResult();

        $positions=[];
        /** @var Poem $poem */
        foreach ($poems as $poem){
            $poemsArray = $this->createQueryBuilder('p')
                ->andWhere('p.position = :position')
                ->setParameter('position',$poem->getPosition())
                ->getQuery()
                ->getResult();
            $positions[$poem->getPosition()]=$poemsArray[array_rand($poemsArray)];
        }
        ksort($positions);
        return $positions;
    }
}
