letunovskiymn_sms_reader:
    resource: "@LetunovskiymnSMSReaderBundle/Controller/"
    type:     annotation
    prefix:   /sms-reader

app:
    resource: '@AppBundle/Controller/'
    type: annotation

letunovskiymn_korablik:
    resource: "@LetunovskiymnKorablikBundle/Controller/"
    prefix: /korablik-bot
    type: annotation