NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

letunovskiymn_poems:
    resource: "@LetunovskiymnPoemsBundle/Controller/"
    type:     annotation
    prefix:   /poems

letunovskiymn_sms_reader:
    resource: "@LetunovskiymnSMSReaderBundle/Controller/"
    type:     annotation
    prefix:   /sms-reader

app:
    resource: '@AppBundle/Controller/'
    type: annotation

letunovskiymn_korablik:
    resource: "@LetunovskiymnKorablikBundle/Controller/"
    prefix: /korablik-bot
    type: annotation