<?php

namespace Letunovskiymn\KorablikBundle\Repository;

/**
 * KeysBotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeysBotRepository extends \Doctrine\ORM\EntityRepository
{
}
